config/routes.rb
Rails.application.routes.draw do
  get 'shop_images/index'
  get 'shop_images/create'
  get 'shop_images/destroy'
  get 'reviews/create'
  get 'reviews/destroy'

  get 'shops/new'
  get 'shops/show'
  get 'shops/create'
  get 'shops/destroy'
  root to: 'toppages#index'

  # get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update]
  
  resources :shops do
    member do
      resources :shop_images
    end
    resources :reviews

  end
  
  resources :favorites, only: [:create, :destroy]

end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :users, through: :favorites
  has_many :reviews
  has_many :users, through: :reviews
  has_many :shop_images
  validates :name, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 50 }
  validates :business_hours, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 50 }
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :new, :create]
  # before_action :correct_user, only: [:destroy]

  def new
    @shop = current_user.shops.build
    # @image = @shop.shop_images.build
  end
  
  def show
    @shop = Shop.find(params[:id])
    @shop_image = @shop.shop_images.last
    @review = current_user.reviews.new
    @reviews = @shop.reviews.order(id: :desc).page(params[:page])
  end

  def create
    @shop = current_user.shops.build(shop_params)
    # @image = @shop.shop_images.build
    if @shop.save
      # @image.save
      flash[:success] = 'お店を投稿をしました'
      redirect_to root_url
    else
      # @shop = current_user.shops.build(shop_params)
      flash.now[:danger] = 'お店の投稿に失敗しました'
      render :new
      # render 'toppages/index'
      # redirect_to root_url, alert: "お店の投稿に失敗しました"
    end
  end

  def destroy
    @shop.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def shop_params
    params.require(:shop).permit(:name, :content, :business_hours, :address, :hp)
  end
  
  def shop_image_params
    params.require(:shop_image).permit(:shop_id, :image)
  end

  
  def correct_user
    @shop = current_user.shop.find_by(id: params[:id])
    unless @shop
      redirect_to root_url
    end
  end  
  
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_shops.html.erb
  <div class="d-flex flex-wrap bd-highlight mb-3 ">
  <% shops.each do |shop| %>
    <div class="card">
      <% if shop.shop_images.present?%>
        <%= image_tag shop.shop_images.last.image.url ,height: '200',width: '200',:alt => 'shopの画像'   %>
      <% else %>
            <image src="/assets/NoImage.png" height="200" width="200" alt="noimage">
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= shop.name %></h5>
        <%= link_to 'more', shop_path(shop) ,class: 'btn btn-primary btn-block'%>
      </div>
    </div>
  <% end %>
  </div>
  <%= paginate shops %>

app/views/shops/new.html.erb
<h1>お店の投稿</h1>
<%= form_with(model: [@shop], local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="form-group">
    <%= f.label :name, 'お店の名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content, '何のお店？' %>
    <%= f.text_area :content, class: 'form-control', row: 5  %>
  </div>

  <div class="form-group">
    <%= f.label :business_hours, '営業時間' %>
    <%= f.text_field :business_hours, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address, '住所' %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :hp, 'ホームページ' %>
    <%= f.text_field :hp, class: 'form-control' %>
  </div>

  <%= f.submit 'お店を共有する', class: 'btn btn-primary btn-block' %>
<% end %>



<div class="mt-3">
  <p><%= link_to '戻る', root_path ,class: 'btn btn-secondary btn-block'%></p>
</div>

app/views/shops/show.html.erb
<h1>店舗名：<%= @shop.name %></h1>
<div class="row">
  <div class="col-sm-4">
    <div class="card" >
    <%if @shop_image.present? %>
      <%= image_tag @shop_image.image.url ,height: '200',width: '200' ,:alt => 'shopの画像' %>
      <% else %>
        <image src="/assets/NoImage.png" height="200" width="200" alt="noimage" %>
      <% end %>
    </div>
    <p class="mt-3"><%= link_to '写真一覧', shop_images_path(@shop) ,class: 'btn btn-primary btn-block'%></p>
    <%= render 'favorites/fav_button', shop: @shop %>

  </div>
  <div class="col-sm-8">
    <table class="table">
      <tr>
        <td>詳細</td>
        <td class="text-left"><%= @shop.content %></td>
      </tr>
      <tr>
        <td>営業時間</td>
        <td class="text-left"><%= @shop.business_hours %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td class="text-left"><%= @shop.address %></td>
      </tr>
      <tr>
        <td>HP</td>
        <td class="text-left"><%= @shop.hp %></td>
      </tr>
    </table>
  </div>
</div>
<div class= "col-sm-8 mt-3">
  <p><%= link_to '口コミを投稿する',new_shop_review_path(@shop)  ,class: 'btn btn-primary btn-block'%></p>
  <ul class="list-unstyled">
    <% @reviews.each do |r| %>
      <li class="media mb-3">
      <% if r.user.image?%>
        <%= image_tag r.user.image.url ,height: '70',width: '70' ,:alt => 'userの画像'%>
      <% else %>
        <image src="/assets/NoImage.png" height="70" width="70" alt="noimage" >
      <% end %>
        <div class="media-body border">
          <div>
            <%= r.user.name %>
          </div>
          <div class="border">
            <p><%= r.review %></p>
          </div>
        </div>
      </li>
    <% end %>
    <%= paginate @reviews %>
  </ul>
</div>