config/routes.rb
Rails.application.routes.draw do
  get 'shop_images/index'
  get 'shop_images/create'
  get 'shop_images/destroy'
  get 'reviews/create'
  get 'reviews/destroy'

  get 'shops/new'
  get 'shops/show'
  get 'shops/create'
  get 'shops/destroy'
  root to: 'toppages#index'

  # get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update]
  
  resources :shops do
    member do
      resources :shop_images
    end
    resources :reviews

  end
  
  resources :favorites, only: [:create, :destroy]

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      # @shop = current_user.shops.build #form_with用
      @shops = Shop.order(id: :desc).page(params[:page])
      
    end
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/toppages/index.html.erb
 <% if logged_in? %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>おいしいお店を共有して口コミを投稿するサービス</h1>
    </div>
  </div>
  <div class = "mb-5">
    <%= link_to 'お店を共有する', shops_new_path(@shop), class: 'btn btn-lg btn-primary btn-block' %>
  </div>
  
  <h2 class = "mb-3">お店一覧</h2>
  <%= render 'shops/shops', shops: @shops %>
 
 <% else %>
    <div class="row mt-5">
      <div class="col-md-6">
        <div class="center jumbotron">
          <h2>おいしいお店を共有して</br>口コミを投稿するサービス</h2>
        </div>
      </div>
      <div class="col-sm-6">
      <%= form_with(url: login_path, scope: :session, local: true) do |f| %>
        <div class="form-group">
          <%= f.label :email, 'Email' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password, 'Password' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <%= f.submit 'Log in', class: 'btn btn-primary btn-block' %>
      <% end %>
      <div class="mt-3">
        <p><%= link_to '新しいアカウントを作成', signup_path ,class: 'btn btn-success btn-block'%></p>
      </div>
    </div>
<% end %>