config/routes.rb
Rails.application.routes.draw do
  get 'shop_images/index'
  get 'shop_images/create'
  get 'shop_images/destroy'
  get 'reviews/create'
  get 'reviews/destroy'

  get 'shops/new'
  get 'shops/show'
  get 'shops/create'
  get 'shops/destroy'
  root to: 'toppages#index'

  # get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update]
  
  resources :shops do
    member do
      resources :shop_images
    end
    resources :reviews

  end
  
  resources :favorites, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  validates :review, presence: true, length: { maximum: 255 }

end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :users, through: :favorites
  has_many :reviews
  has_many :users, through: :reviews
  has_many :shop_images
  validates :name, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 50 }
  validates :business_hours, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 50 }
end

app/models/shop_image.rb
class ShopImage < ApplicationRecord
  belongs_to :shop
  mount_uploader :image, ImageUploader
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                  uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :shops
  has_many :favorites
  has_many :fav_shops, through: :favorites, source: :shop
  
  has_many :reviews
  has_many :comment, through: :reviews, source: :shop
  
  mount_uploader :image, ImageUploader

  def favorite(shop)
    self.favorites.find_or_create_by(shop_id: shop.id)
  end
  
  def unfavorite(shop)
    favorite = self.favorites.find_by(shop_id: shop.id)
    favorite.destroy if favorite
  end
  
  def favoring?(shop)
    self.fav_shops.include?(shop)
  end
  
  # def review(shop)
  #   self.reviews.find_or_create_by(shop_id: shop.id)
  # end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :require_user_logged_in

  def create
    shop = Shop.find(params[:favorite_id])
    current_user.favorite(shop)
    flash[:success] = 'お気に入りに追加しました。'
    redirect_to root_url    
  end

  def destroy
    shop = Shop.find(params[:favorite_id])
    current_user.unfavorite(shop)
    flash[:success] = 'お気に入りを解除しました。'
    redirect_to root_url    
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :require_user_logged_in

  def new
    @review = current_user.reviews.new
    @shop = Shop.find(params[:shop_id])
  end
  
  def create
    @review = current_user.reviews.new(review_params)
    shop = Shop.find(params[:shop_id])
    @review.shop_id = shop.id

    if @review.save
      flash[:success] = '口コミを投稿をしました'
       redirect_to root_url
    else
      @shop = Shop.find(params[:shop_id])
      @review = current_user.reviews.build(review_params)
      flash.now[:danger] = '口コミの投稿に失敗しました'
      # redirect_to root_url,alert: "口コミの投稿に失敗しました"
      # render 'toppages/index'
      render :new
    end
  end

  def destroy
  end

  private
  
  def review_params
    params.require(:review).permit(:user_id, :shop_id, :review)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      #render :new
      # redirect_to root_url
      render 'toppages/index'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :new, :create]
  # before_action :correct_user, only: [:destroy]

  def new
    @shop = current_user.shops.build
    # @image = @shop.shop_images.build
  end
  
  def show
    @shop = Shop.find(params[:id])
    @shop_image = @shop.shop_images.last
    @review = current_user.reviews.new
    @reviews = @shop.reviews.order(id: :desc).page(params[:page])
  end

  def create
    @shop = current_user.shops.build(shop_params)
    # @image = @shop.shop_images.build
    if @shop.save
      # @image.save
      flash[:success] = 'お店を投稿をしました'
      redirect_to root_url
    else
      # @shop = current_user.shops.build(shop_params)
      flash.now[:danger] = 'お店の投稿に失敗しました'
      render :new
      # render 'toppages/index'
      # redirect_to root_url, alert: "お店の投稿に失敗しました"
    end
  end

  def destroy
    @shop.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def shop_params
    params.require(:shop).permit(:name, :content, :business_hours, :address, :hp)
  end
  
  def shop_image_params
    params.require(:shop_image).permit(:shop_id, :image)
  end

  
  def correct_user
    @shop = current_user.shop.find_by(id: params[:id])
    unless @shop
      redirect_to root_url
    end
  end  
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      # @shop = current_user.shops.build #form_with用
      @shops = Shop.order(id: :desc).page(params[:page])
      
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :update]

  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    # @shops = Shop.find(params[:id])
    @fav_shops = @user.fav_shops.order(id: :desc).page(params[:page])
  end

  def new
    @user = User.new
    
  end

  def create
    @user = User.new(user_params)
    @user.image = "NoImage.jpg"

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
  
  def update
  @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end
  
  # def likes
  #   @user = User.find(params[:id])
  #   @shops = Shop.find(params[:id])
  #   @fav_shops = @user.fav_shops.order(id: :desc).page(params[:page])
  # end
  
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile, :image)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/shop_images_helper.rb
module ShopImagesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
#   #画像表示に直す
#   def gravatar_url(user, options = { size: 80 })
#     gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
#     size = options[:size]
#     "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
#   end
 end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
<% if logged_in? %>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Top</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
          <ul class="dropdown-menu dropdown-menu-right">
            <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
            <li class="dropdown-divider"></li>
            <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
  </nav>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GourmetReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>